{{- include "lareira-vigia.validate" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lareira-vigia.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lareira-vigia.labels" . | nindent 4 }}
